name: fluttercircles
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.5.3
#  cloud_firestore: ^2.5.3
  image_picker: ^0.8.4+2
#  firebase_storage: ^10.0.3
  firebase_storage: ^10.0.3
  firebase_auth: ^3.1.1
#  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.1
  geolocator: ^7.6.2
#  uuid: ^3.0.4
  uuid: ^3.0.4
#  image: ^3.0.5
  image: ^3.0.5
  animator: ^3.1.0
  cupertino_icons: ^1.0.3
#  path_provider:
  path_provider: ^2.0.5
  firebase_messaging: ^10.0.7
#  firebase_messaging: ^10.0.7
  firebase_analytics: ^8.3.2
#  firebase_analytics: ^8.3.2
  timeago: ^3.1.0
  cached_network_image:
  flutter_svg:
  google_maps_flutter: ^2.0.10
  location_permissions: ^4.0.0
  firebase_core:
  provider: ^6.0.1
  font_awesome_flutter: ^9.0.0
  workmanager: ^0.4.1
  shared_preferences: ^2.0.8
  location:
  location_web:
  flutter_background_geolocation: ^4.3.0
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.0
#  background_fetch: ^1.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg
